// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game_type.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strconv "strconv"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 日志操作类型
type LogType int32

const (
	LOG_TYPE0 LogType = 0
	LOG_TYPE1 LogType = 1
)

var LogType_name = map[int32]string{
	0: "LOG_TYPE0",
	1: "LOG_TYPE1",
}
var LogType_value = map[string]int32{
	"LOG_TYPE0": 0,
	"LOG_TYPE1": 1,
}

func (LogType) EnumDescriptor() ([]byte, []int) { return fileDescriptorGameType, []int{0} }

// 关卡类型
type GateType int32

const (
	GATE_TYPE0 GateType = 0
	GATE_TYPE1 GateType = 1
	GATE_TYPE2 GateType = 2
)

var GateType_name = map[int32]string{
	0: "GATE_TYPE0",
	1: "GATE_TYPE1",
	2: "GATE_TYPE2",
}
var GateType_value = map[string]int32{
	"GATE_TYPE0": 0,
	"GATE_TYPE1": 1,
	"GATE_TYPE2": 2,
}

func (GateType) EnumDescriptor() ([]byte, []int) { return fileDescriptorGameType, []int{1} }

// 登出类型
type OutType int32

const (
	OUT_TYPE0 OutType = 0
	OUT_TYPE1 OutType = 1
	OUT_TYPE2 OutType = 2
)

var OutType_name = map[int32]string{
	0: "OUT_TYPE0",
	1: "OUT_TYPE1",
	2: "OUT_TYPE2",
}
var OutType_value = map[string]int32{
	"OUT_TYPE0": 0,
	"OUT_TYPE1": 1,
	"OUT_TYPE2": 2,
}

func (OutType) EnumDescriptor() ([]byte, []int) { return fileDescriptorGameType, []int{2} }

// 道具类型
type PropType int32

const (
	PROP_TYPE0  PropType = 0
	PROP_TYPE1  PropType = 1
	PROP_TYPE2  PropType = 2
	PROP_TYPE3  PropType = 3
	PROP_TYPE4  PropType = 4
	PROP_TYPE5  PropType = 5
	PROP_TYPE6  PropType = 6
	PROP_TYPE7  PropType = 7
	PROP_TYPE8  PropType = 8
	PROP_TYPE10 PropType = 10
	PROP_TYPE11 PropType = 11
	PROP_TYPE12 PropType = 12
)

var PropType_name = map[int32]string{
	0:  "PROP_TYPE0",
	1:  "PROP_TYPE1",
	2:  "PROP_TYPE2",
	3:  "PROP_TYPE3",
	4:  "PROP_TYPE4",
	5:  "PROP_TYPE5",
	6:  "PROP_TYPE6",
	7:  "PROP_TYPE7",
	8:  "PROP_TYPE8",
	10: "PROP_TYPE10",
	11: "PROP_TYPE11",
	12: "PROP_TYPE12",
}
var PropType_value = map[string]int32{
	"PROP_TYPE0":  0,
	"PROP_TYPE1":  1,
	"PROP_TYPE2":  2,
	"PROP_TYPE3":  3,
	"PROP_TYPE4":  4,
	"PROP_TYPE5":  5,
	"PROP_TYPE6":  6,
	"PROP_TYPE7":  7,
	"PROP_TYPE8":  8,
	"PROP_TYPE10": 10,
	"PROP_TYPE11": 11,
	"PROP_TYPE12": 12,
}

func (PropType) EnumDescriptor() ([]byte, []int) { return fileDescriptorGameType, []int{3} }

// 支付方式
type PayWay int32

const (
	PAY_WAY0 PayWay = 0
	PAY_WAY1 PayWay = 1
	PAY_WAY2 PayWay = 2
)

var PayWay_name = map[int32]string{
	0: "PAY_WAY0",
	1: "PAY_WAY1",
	2: "PAY_WAY2",
}
var PayWay_value = map[string]int32{
	"PAY_WAY0": 0,
	"PAY_WAY1": 1,
	"PAY_WAY2": 2,
}

func (PayWay) EnumDescriptor() ([]byte, []int) { return fileDescriptorGameType, []int{4} }

// 商品状态
type ShopStatus int32

const (
	SHOP_STATUS0 ShopStatus = 0
	SHOP_STATUS1 ShopStatus = 1
	SHOP_STATUS2 ShopStatus = 2
)

var ShopStatus_name = map[int32]string{
	0: "SHOP_STATUS0",
	1: "SHOP_STATUS1",
	2: "SHOP_STATUS2",
}
var ShopStatus_value = map[string]int32{
	"SHOP_STATUS0": 0,
	"SHOP_STATUS1": 1,
	"SHOP_STATUS2": 2,
}

func (ShopStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptorGameType, []int{5} }

// 登录奖励类型
type LoginPrizeType int32

const (
	LoginPrizeSelect LoginPrizeType = 0
	LoginPrizeDraw   LoginPrizeType = 1
)

var LoginPrizeType_name = map[int32]string{
	0: "LoginPrizeSelect",
	1: "LoginPrizeDraw",
}
var LoginPrizeType_value = map[string]int32{
	"LoginPrizeSelect": 0,
	"LoginPrizeDraw":   1,
}

func (LoginPrizeType) EnumDescriptor() ([]byte, []int) { return fileDescriptorGameType, []int{6} }

func init() {
	proto.RegisterEnum("pb.LogType", LogType_name, LogType_value)
	proto.RegisterEnum("pb.GateType", GateType_name, GateType_value)
	proto.RegisterEnum("pb.OutType", OutType_name, OutType_value)
	proto.RegisterEnum("pb.PropType", PropType_name, PropType_value)
	proto.RegisterEnum("pb.PayWay", PayWay_name, PayWay_value)
	proto.RegisterEnum("pb.ShopStatus", ShopStatus_name, ShopStatus_value)
	proto.RegisterEnum("pb.LoginPrizeType", LoginPrizeType_name, LoginPrizeType_value)
}
func (x LogType) String() string {
	s, ok := LogType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x GateType) String() string {
	s, ok := GateType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x OutType) String() string {
	s, ok := OutType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x PropType) String() string {
	s, ok := PropType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x PayWay) String() string {
	s, ok := PayWay_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ShopStatus) String() string {
	s, ok := ShopStatus_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x LoginPrizeType) String() string {
	s, ok := LoginPrizeType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

func init() { proto.RegisterFile("game_type.proto", fileDescriptorGameType) }

var fileDescriptorGameType = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd2, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x06, 0xe0, 0x0e, 0xf7, 0x5e, 0xe8, 0x3d, 0x20, 0x9c, 0x4c, 0x5c, 0xcf, 0xd6, 0xa4, 0x31,
	0x06, 0x8a, 0xa2, 0x61, 0x57, 0x22, 0xc1, 0x05, 0x49, 0x27, 0xb6, 0x84, 0xb0, 0x6a, 0x8a, 0x69,
	0x90, 0x44, 0x6d, 0x53, 0x87, 0x98, 0xba, 0xf2, 0x11, 0x7c, 0x0c, 0x1f, 0xc5, 0x8d, 0x09, 0x4b,
	0x97, 0x32, 0x6e, 0x5c, 0xf2, 0x08, 0x66, 0x50, 0x68, 0x67, 0xf9, 0xfd, 0x39, 0xa7, 0x7f, 0x4e,
	0x5b, 0x68, 0xcc, 0xc2, 0xdb, 0x28, 0x10, 0x59, 0x12, 0x1d, 0x25, 0x69, 0x2c, 0x62, 0x5a, 0x4a,
	0xa6, 0xd6, 0x01, 0x54, 0x86, 0xf1, 0xcc, 0xcf, 0x92, 0x88, 0xee, 0xc1, 0xff, 0xa1, 0x3b, 0x08,
	0xfc, 0x09, 0xef, 0x37, 0xd1, 0x28, 0xb2, 0x85, 0xc4, 0xea, 0x82, 0x39, 0x08, 0x45, 0xb4, 0x99,
	0xac, 0x03, 0x0c, 0x1c, 0xbf, 0xbf, 0x1b, 0x2d, 0xba, 0x85, 0x44, 0xb3, 0x8d, 0x25, 0xab, 0x03,
	0x15, 0x77, 0x21, 0xb6, 0x25, 0xee, 0xc8, 0x2f, 0x96, 0x6c, 0xa9, 0x16, 0x0b, 0x54, 0x7b, 0x6f,
	0x04, 0x4c, 0x9e, 0xc6, 0xc9, 0xb6, 0x94, 0x5f, 0xba, 0xbc, 0x58, 0xba, 0xf3, 0x6f, 0xe9, 0xce,
	0x36, 0x96, 0x34, 0xb7, 0xf1, 0x8f, 0xe6, 0x63, 0xfc, 0xab, 0xf9, 0x04, 0xff, 0x69, 0xee, 0x60,
	0x59, 0xf3, 0x29, 0x56, 0x34, 0x9f, 0xa1, 0x49, 0x1b, 0x50, 0xcd, 0xfb, 0x9b, 0x08, 0x7a, 0xd0,
	0xc2, 0xaa, 0x1e, 0xd8, 0x58, 0xb3, 0x6c, 0x28, 0xf3, 0x30, 0x1b, 0x87, 0x19, 0xad, 0x81, 0xc9,
	0x9d, 0x49, 0x30, 0x76, 0x26, 0xea, 0x94, 0x5c, 0xea, 0x90, 0x5c, 0xea, 0x1d, 0xf4, 0x00, 0xbc,
	0xeb, 0x38, 0xf1, 0x44, 0x28, 0x16, 0xf7, 0x14, 0xa1, 0xe6, 0x5d, 0xb8, 0x3c, 0xf0, 0x7c, 0xc7,
	0x1f, 0x79, 0x6a, 0x57, 0x4f, 0xd4, 0xbe, 0x9e, 0xa8, 0x67, 0x74, 0xa1, 0x3e, 0x8c, 0x67, 0xf3,
	0x3b, 0x9e, 0xce, 0x1f, 0x7f, 0xbe, 0xe0, 0x3e, 0x60, 0x9e, 0x78, 0xd1, 0x4d, 0x74, 0x25, 0xd0,
	0xa0, 0xb4, 0x38, 0x77, 0x9e, 0x86, 0x0f, 0x48, 0x7a, 0x87, 0xcb, 0x15, 0x33, 0xde, 0x57, 0xcc,
	0x58, 0xaf, 0x18, 0x79, 0x92, 0x8c, 0xbc, 0x48, 0x46, 0x5e, 0x25, 0x23, 0x4b, 0xc9, 0xc8, 0x87,
	0x64, 0xe4, 0x4b, 0x32, 0x63, 0x2d, 0x19, 0x79, 0xfe, 0x64, 0xc6, 0xb4, 0xbc, 0xf9, 0xb3, 0xda,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x82, 0xf7, 0xf4, 0x24, 0x6c, 0x02, 0x00, 0x00,
}
