// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game_play.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 结算数据
type COverData struct {
	Type   GateType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.GateType" json:"type,omitempty"`
	Gateid int32    `protobuf:"varint,2,opt,name=gateid,proto3" json:"gateid,omitempty"`
	Stars  int32    `protobuf:"varint,3,opt,name=stars,proto3" json:"stars,omitempty"`
}

func (m *COverData) Reset()                    { *m = COverData{} }
func (*COverData) ProtoMessage()               {}
func (*COverData) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{0} }

func (m *COverData) GetType() GateType {
	if m != nil {
		return m.Type
	}
	return GATE_TYPE0
}

func (m *COverData) GetGateid() int32 {
	if m != nil {
		return m.Gateid
	}
	return 0
}

func (m *COverData) GetStars() int32 {
	if m != nil {
		return m.Stars
	}
	return 0
}

type SOverData struct {
	CardInfo int32       `protobuf:"varint,1,opt,name=cardInfo,proto3" json:"cardInfo,omitempty"`
	NextGate *GateData   `protobuf:"bytes,2,opt,name=nextGate" json:"nextGate,omitempty"`
	PropInfo []*PropData `protobuf:"bytes,3,rep,name=propInfo" json:"propInfo,omitempty"`
	Error    ErrCode     `protobuf:"varint,4,opt,name=error,proto3,enum=pb.ErrCode" json:"error,omitempty"`
}

func (m *SOverData) Reset()                    { *m = SOverData{} }
func (*SOverData) ProtoMessage()               {}
func (*SOverData) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{1} }

func (m *SOverData) GetCardInfo() int32 {
	if m != nil {
		return m.CardInfo
	}
	return 0
}

func (m *SOverData) GetNextGate() *GateData {
	if m != nil {
		return m.NextGate
	}
	return nil
}

func (m *SOverData) GetPropInfo() []*PropData {
	if m != nil {
		return m.PropInfo
	}
	return nil
}

func (m *SOverData) GetError() ErrCode {
	if m != nil {
		return m.Error
	}
	return OK
}

// 卡牌
type CCard struct {
}

func (m *CCard) Reset()                    { *m = CCard{} }
func (*CCard) ProtoMessage()               {}
func (*CCard) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{2} }

type SCard struct {
	LeftTimes int32       `protobuf:"varint,1,opt,name=leftTimes,proto3" json:"leftTimes,omitempty"`
	PropInfo  []*PropData `protobuf:"bytes,3,rep,name=propInfo" json:"propInfo,omitempty"`
	Error     ErrCode     `protobuf:"varint,2,opt,name=error,proto3,enum=pb.ErrCode" json:"error,omitempty"`
}

func (m *SCard) Reset()                    { *m = SCard{} }
func (*SCard) ProtoMessage()               {}
func (*SCard) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{3} }

func (m *SCard) GetLeftTimes() int32 {
	if m != nil {
		return m.LeftTimes
	}
	return 0
}

func (m *SCard) GetPropInfo() []*PropData {
	if m != nil {
		return m.PropInfo
	}
	return nil
}

func (m *SCard) GetError() ErrCode {
	if m != nil {
		return m.Error
	}
	return OK
}

// 登录奖励
type CLoginPrize struct {
	Type LoginPrizeType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.LoginPrizeType" json:"type,omitempty"`
	Day  uint32         `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
}

func (m *CLoginPrize) Reset()                    { *m = CLoginPrize{} }
func (*CLoginPrize) ProtoMessage()               {}
func (*CLoginPrize) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{4} }

func (m *CLoginPrize) GetType() LoginPrizeType {
	if m != nil {
		return m.Type
	}
	return LoginPrizeSelect
}

func (m *CLoginPrize) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type SLoginPrize struct {
	Type  LoginPrizeType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.LoginPrizeType" json:"type,omitempty"`
	List  []*LoginPrize  `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Error ErrCode        `protobuf:"varint,3,opt,name=error,proto3,enum=pb.ErrCode" json:"error,omitempty"`
}

func (m *SLoginPrize) Reset()                    { *m = SLoginPrize{} }
func (*SLoginPrize) ProtoMessage()               {}
func (*SLoginPrize) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{5} }

func (m *SLoginPrize) GetType() LoginPrizeType {
	if m != nil {
		return m.Type
	}
	return LoginPrizeSelect
}

func (m *SLoginPrize) GetList() []*LoginPrize {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SLoginPrize) GetError() ErrCode {
	if m != nil {
		return m.Error
	}
	return OK
}

// 使用道具
type CUseProp struct {
	Ptype PropType `protobuf:"varint,1,opt,name=ptype,proto3,enum=pb.PropType" json:"ptype,omitempty"`
}

func (m *CUseProp) Reset()                    { *m = CUseProp{} }
func (*CUseProp) ProtoMessage()               {}
func (*CUseProp) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{6} }

func (m *CUseProp) GetPtype() PropType {
	if m != nil {
		return m.Ptype
	}
	return PROP_TYPE0
}

type SUseProp struct {
	Ptype PropType `protobuf:"varint,1,opt,name=ptype,proto3,enum=pb.PropType" json:"ptype,omitempty"`
	Error ErrCode  `protobuf:"varint,2,opt,name=error,proto3,enum=pb.ErrCode" json:"error,omitempty"`
}

func (m *SUseProp) Reset()                    { *m = SUseProp{} }
func (*SUseProp) ProtoMessage()               {}
func (*SUseProp) Descriptor() ([]byte, []int) { return fileDescriptorGamePlay, []int{7} }

func (m *SUseProp) GetPtype() PropType {
	if m != nil {
		return m.Ptype
	}
	return PROP_TYPE0
}

func (m *SUseProp) GetError() ErrCode {
	if m != nil {
		return m.Error
	}
	return OK
}

func init() {
	proto.RegisterType((*COverData)(nil), "pb.COverData")
	proto.RegisterType((*SOverData)(nil), "pb.SOverData")
	proto.RegisterType((*CCard)(nil), "pb.CCard")
	proto.RegisterType((*SCard)(nil), "pb.SCard")
	proto.RegisterType((*CLoginPrize)(nil), "pb.CLoginPrize")
	proto.RegisterType((*SLoginPrize)(nil), "pb.SLoginPrize")
	proto.RegisterType((*CUseProp)(nil), "pb.CUseProp")
	proto.RegisterType((*SUseProp)(nil), "pb.SUseProp")
}
func (this *COverData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*COverData)
	if !ok {
		that2, ok := that.(COverData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Gateid != that1.Gateid {
		return false
	}
	if this.Stars != that1.Stars {
		return false
	}
	return true
}
func (this *SOverData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SOverData)
	if !ok {
		that2, ok := that.(SOverData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CardInfo != that1.CardInfo {
		return false
	}
	if !this.NextGate.Equal(that1.NextGate) {
		return false
	}
	if len(this.PropInfo) != len(that1.PropInfo) {
		return false
	}
	for i := range this.PropInfo {
		if !this.PropInfo[i].Equal(that1.PropInfo[i]) {
			return false
		}
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (this *CCard) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CCard)
	if !ok {
		that2, ok := that.(CCard)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *SCard) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SCard)
	if !ok {
		that2, ok := that.(SCard)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LeftTimes != that1.LeftTimes {
		return false
	}
	if len(this.PropInfo) != len(that1.PropInfo) {
		return false
	}
	for i := range this.PropInfo {
		if !this.PropInfo[i].Equal(that1.PropInfo[i]) {
			return false
		}
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (this *CLoginPrize) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CLoginPrize)
	if !ok {
		that2, ok := that.(CLoginPrize)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Day != that1.Day {
		return false
	}
	return true
}
func (this *SLoginPrize) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SLoginPrize)
	if !ok {
		that2, ok := that.(SLoginPrize)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if len(this.List) != len(that1.List) {
		return false
	}
	for i := range this.List {
		if !this.List[i].Equal(that1.List[i]) {
			return false
		}
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (this *CUseProp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CUseProp)
	if !ok {
		that2, ok := that.(CUseProp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Ptype != that1.Ptype {
		return false
	}
	return true
}
func (this *SUseProp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SUseProp)
	if !ok {
		that2, ok := that.(SUseProp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Ptype != that1.Ptype {
		return false
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (this *COverData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.COverData{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Gateid: "+fmt.Sprintf("%#v", this.Gateid)+",\n")
	s = append(s, "Stars: "+fmt.Sprintf("%#v", this.Stars)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SOverData) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&pb.SOverData{")
	s = append(s, "CardInfo: "+fmt.Sprintf("%#v", this.CardInfo)+",\n")
	if this.NextGate != nil {
		s = append(s, "NextGate: "+fmt.Sprintf("%#v", this.NextGate)+",\n")
	}
	if this.PropInfo != nil {
		s = append(s, "PropInfo: "+fmt.Sprintf("%#v", this.PropInfo)+",\n")
	}
	s = append(s, "Error: "+fmt.Sprintf("%#v", this.Error)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CCard) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&pb.CCard{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SCard) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.SCard{")
	s = append(s, "LeftTimes: "+fmt.Sprintf("%#v", this.LeftTimes)+",\n")
	if this.PropInfo != nil {
		s = append(s, "PropInfo: "+fmt.Sprintf("%#v", this.PropInfo)+",\n")
	}
	s = append(s, "Error: "+fmt.Sprintf("%#v", this.Error)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CLoginPrize) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pb.CLoginPrize{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Day: "+fmt.Sprintf("%#v", this.Day)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SLoginPrize) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.SLoginPrize{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	if this.List != nil {
		s = append(s, "List: "+fmt.Sprintf("%#v", this.List)+",\n")
	}
	s = append(s, "Error: "+fmt.Sprintf("%#v", this.Error)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CUseProp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&pb.CUseProp{")
	s = append(s, "Ptype: "+fmt.Sprintf("%#v", this.Ptype)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SUseProp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pb.SUseProp{")
	s = append(s, "Ptype: "+fmt.Sprintf("%#v", this.Ptype)+",\n")
	s = append(s, "Error: "+fmt.Sprintf("%#v", this.Error)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringGamePlay(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *COverData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *COverData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Type))
	}
	if m.Gateid != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Gateid))
	}
	if m.Stars != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Stars))
	}
	return i, nil
}

func (m *SOverData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SOverData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.CardInfo != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.CardInfo))
	}
	if m.NextGate != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.NextGate.Size()))
		n1, err := m.NextGate.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.PropInfo) > 0 {
		for _, msg := range m.PropInfo {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintGamePlay(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Error != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Error))
	}
	return i, nil
}

func (m *CCard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CCard) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *SCard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SCard) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.LeftTimes != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.LeftTimes))
	}
	if m.Error != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Error))
	}
	if len(m.PropInfo) > 0 {
		for _, msg := range m.PropInfo {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintGamePlay(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *CLoginPrize) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CLoginPrize) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Type))
	}
	if m.Day != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Day))
	}
	return i, nil
}

func (m *SLoginPrize) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SLoginPrize) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Type))
	}
	if len(m.List) > 0 {
		for _, msg := range m.List {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGamePlay(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Error != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Error))
	}
	return i, nil
}

func (m *CUseProp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CUseProp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Ptype != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Ptype))
	}
	return i, nil
}

func (m *SUseProp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SUseProp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Ptype != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Ptype))
	}
	if m.Error != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGamePlay(dAtA, i, uint64(m.Error))
	}
	return i, nil
}

func encodeVarintGamePlay(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *COverData) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovGamePlay(uint64(m.Type))
	}
	if m.Gateid != 0 {
		n += 1 + sovGamePlay(uint64(m.Gateid))
	}
	if m.Stars != 0 {
		n += 1 + sovGamePlay(uint64(m.Stars))
	}
	return n
}

func (m *SOverData) Size() (n int) {
	var l int
	_ = l
	if m.CardInfo != 0 {
		n += 1 + sovGamePlay(uint64(m.CardInfo))
	}
	if m.NextGate != nil {
		l = m.NextGate.Size()
		n += 1 + l + sovGamePlay(uint64(l))
	}
	if len(m.PropInfo) > 0 {
		for _, e := range m.PropInfo {
			l = e.Size()
			n += 1 + l + sovGamePlay(uint64(l))
		}
	}
	if m.Error != 0 {
		n += 1 + sovGamePlay(uint64(m.Error))
	}
	return n
}

func (m *CCard) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *SCard) Size() (n int) {
	var l int
	_ = l
	if m.LeftTimes != 0 {
		n += 1 + sovGamePlay(uint64(m.LeftTimes))
	}
	if m.Error != 0 {
		n += 1 + sovGamePlay(uint64(m.Error))
	}
	if len(m.PropInfo) > 0 {
		for _, e := range m.PropInfo {
			l = e.Size()
			n += 1 + l + sovGamePlay(uint64(l))
		}
	}
	return n
}

func (m *CLoginPrize) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovGamePlay(uint64(m.Type))
	}
	if m.Day != 0 {
		n += 1 + sovGamePlay(uint64(m.Day))
	}
	return n
}

func (m *SLoginPrize) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovGamePlay(uint64(m.Type))
	}
	if len(m.List) > 0 {
		for _, e := range m.List {
			l = e.Size()
			n += 1 + l + sovGamePlay(uint64(l))
		}
	}
	if m.Error != 0 {
		n += 1 + sovGamePlay(uint64(m.Error))
	}
	return n
}

func (m *CUseProp) Size() (n int) {
	var l int
	_ = l
	if m.Ptype != 0 {
		n += 1 + sovGamePlay(uint64(m.Ptype))
	}
	return n
}

func (m *SUseProp) Size() (n int) {
	var l int
	_ = l
	if m.Ptype != 0 {
		n += 1 + sovGamePlay(uint64(m.Ptype))
	}
	if m.Error != 0 {
		n += 1 + sovGamePlay(uint64(m.Error))
	}
	return n
}

func sovGamePlay(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGamePlay(x uint64) (n int) {
	return sovGamePlay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *COverData) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&COverData{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Gateid:` + fmt.Sprintf("%v", this.Gateid) + `,`,
		`Stars:` + fmt.Sprintf("%v", this.Stars) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SOverData) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SOverData{`,
		`CardInfo:` + fmt.Sprintf("%v", this.CardInfo) + `,`,
		`NextGate:` + strings.Replace(fmt.Sprintf("%v", this.NextGate), "GateData", "GateData", 1) + `,`,
		`PropInfo:` + strings.Replace(fmt.Sprintf("%v", this.PropInfo), "PropData", "PropData", 1) + `,`,
		`Error:` + fmt.Sprintf("%v", this.Error) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CCard) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CCard{`,
		`}`,
	}, "")
	return s
}
func (this *SCard) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SCard{`,
		`LeftTimes:` + fmt.Sprintf("%v", this.LeftTimes) + `,`,
		`Error:` + fmt.Sprintf("%v", this.Error) + `,`,
		`PropInfo:` + strings.Replace(fmt.Sprintf("%v", this.PropInfo), "PropData", "PropData", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CLoginPrize) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CLoginPrize{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Day:` + fmt.Sprintf("%v", this.Day) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SLoginPrize) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SLoginPrize{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`List:` + strings.Replace(fmt.Sprintf("%v", this.List), "LoginPrize", "LoginPrize", 1) + `,`,
		`Error:` + fmt.Sprintf("%v", this.Error) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CUseProp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CUseProp{`,
		`Ptype:` + fmt.Sprintf("%v", this.Ptype) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SUseProp) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SUseProp{`,
		`Ptype:` + fmt.Sprintf("%v", this.Ptype) + `,`,
		`Error:` + fmt.Sprintf("%v", this.Error) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGamePlay(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *COverData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: COverData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: COverData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (GateType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gateid", wireType)
			}
			m.Gateid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Gateid |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stars", wireType)
			}
			m.Stars = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stars |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SOverData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SOverData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SOverData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CardInfo", wireType)
			}
			m.CardInfo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CardInfo |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextGate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGamePlay
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NextGate == nil {
				m.NextGate = &GateData{}
			}
			if err := m.NextGate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PropInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGamePlay
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PropInfo = append(m.PropInfo, &PropData{})
			if err := m.PropInfo[len(m.PropInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			m.Error = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Error |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CCard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CCard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CCard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SCard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SCard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SCard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeftTimes", wireType)
			}
			m.LeftTimes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeftTimes |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			m.Error = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Error |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PropInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGamePlay
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PropInfo = append(m.PropInfo, &PropData{})
			if err := m.PropInfo[len(m.PropInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CLoginPrize) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CLoginPrize: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CLoginPrize: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (LoginPrizeType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Day", wireType)
			}
			m.Day = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Day |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SLoginPrize) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SLoginPrize: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SLoginPrize: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (LoginPrizeType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGamePlay
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.List = append(m.List, &LoginPrize{})
			if err := m.List[len(m.List)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			m.Error = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Error |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CUseProp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CUseProp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CUseProp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ptype", wireType)
			}
			m.Ptype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ptype |= (PropType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SUseProp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SUseProp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SUseProp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ptype", wireType)
			}
			m.Ptype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ptype |= (PropType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			m.Error = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Error |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGamePlay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGamePlay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGamePlay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGamePlay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGamePlay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGamePlay
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGamePlay
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGamePlay(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGamePlay = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGamePlay   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("game_play.proto", fileDescriptorGamePlay) }

var fileDescriptorGamePlay = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x8b, 0xd4, 0x30,
	0x18, 0xc6, 0x9b, 0x76, 0xba, 0x76, 0xde, 0xea, 0x28, 0x41, 0xa4, 0x0c, 0x12, 0x6a, 0x0e, 0x32,
	0x07, 0xe9, 0x41, 0xbf, 0x81, 0x55, 0x16, 0x41, 0x70, 0x6d, 0xd7, 0x93, 0x07, 0x49, 0xb7, 0xd9,
	0xa1, 0x30, 0x3b, 0x09, 0x69, 0x14, 0x2b, 0x1e, 0xfc, 0x08, 0x7e, 0x02, 0xcf, 0x7e, 0x14, 0x8f,
	0x7b, 0xf4, 0xe8, 0xd4, 0x8b, 0xc7, 0xfd, 0x08, 0x92, 0xa4, 0x3b, 0x75, 0x85, 0x81, 0xd1, 0x5b,
	0xde, 0xf7, 0xf9, 0xe5, 0x79, 0xff, 0x24, 0x70, 0x73, 0xc9, 0xce, 0xf8, 0x1b, 0xb9, 0x62, 0x5d,
	0x26, 0x95, 0xd0, 0x02, 0xfb, 0xb2, 0x9a, 0xbb, 0xe4, 0x89, 0xa8, 0xb9, 0x4b, 0xce, 0x67, 0x8e,
	0x7a, 0x5b, 0x0d, 0xb1, 0x03, 0x74, 0x27, 0x07, 0x80, 0xbe, 0x86, 0x69, 0xfe, 0xe2, 0x1d, 0x57,
	0x4f, 0x98, 0x66, 0x38, 0x85, 0x89, 0x91, 0x12, 0x94, 0xa2, 0xc5, 0xec, 0xe1, 0xf5, 0x4c, 0x56,
	0xd9, 0x21, 0xd3, 0xfc, 0xb8, 0x93, 0xbc, 0xb0, 0x0a, 0xbe, 0x03, 0x07, 0x4b, 0xa6, 0x79, 0x53,
	0x27, 0x7e, 0x8a, 0x16, 0x61, 0x31, 0x44, 0xf8, 0x36, 0x84, 0xad, 0x66, 0xaa, 0x4d, 0x02, 0x9b,
	0x76, 0x01, 0xfd, 0x82, 0x60, 0x5a, 0x6e, 0xdd, 0xe7, 0x10, 0x9d, 0x30, 0x55, 0x3f, 0x5b, 0x9f,
	0x0a, 0x5b, 0x21, 0x2c, 0xb6, 0x31, 0x5e, 0x40, 0xb4, 0xe6, 0xef, 0xb5, 0xa9, 0x66, 0x9d, 0xe3,
	0xb1, 0xba, 0xb9, 0x5b, 0x6c, 0x55, 0x43, 0x4a, 0x25, 0xa4, 0x75, 0x09, 0xd2, 0xe0, 0x92, 0x3c,
	0x52, 0x42, 0x3a, 0xf2, 0x52, 0xc5, 0xf7, 0x20, 0xe4, 0x4a, 0x09, 0x95, 0x4c, 0xec, 0x38, 0xb1,
	0xc1, 0x9e, 0x2a, 0x95, 0x8b, 0x9a, 0x17, 0x4e, 0xa1, 0xd7, 0x20, 0xcc, 0x73, 0xa6, 0x6a, 0xaa,
	0x20, 0x2c, 0xcd, 0x01, 0xdf, 0x85, 0xe9, 0x8a, 0x9f, 0xea, 0xe3, 0xe6, 0x8c, 0xb7, 0x43, 0x97,
	0x63, 0x62, 0xb4, 0xf4, 0x77, 0x59, 0xee, 0xdf, 0x1f, 0x3d, 0x84, 0x38, 0x7f, 0x2e, 0x96, 0xcd,
	0xfa, 0x48, 0x35, 0x1f, 0x38, 0xbe, 0x7f, 0x65, 0xf9, 0xd8, 0x5c, 0x1a, 0xd5, 0x3f, 0x9e, 0xe0,
	0x16, 0x04, 0x35, 0xeb, 0x6c, 0x07, 0x37, 0x0a, 0x73, 0xa4, 0x1f, 0x21, 0x2e, 0xff, 0xc3, 0x88,
	0xc2, 0x64, 0xd5, 0xb4, 0x3a, 0xf1, 0x6d, 0x97, 0xb3, 0xab, 0x5c, 0x61, 0xb5, 0x71, 0xe0, 0x60,
	0xe7, 0x0e, 0x33, 0x88, 0xf2, 0x57, 0x2d, 0x37, 0x03, 0x62, 0x0a, 0xa1, 0xfc, 0xfb, 0x07, 0x19,
	0xc1, 0x56, 0x75, 0x12, 0x7d, 0x09, 0x51, 0xf9, 0x0f, 0xfc, 0x1e, 0x3b, 0x7f, 0xfc, 0xe0, 0x7c,
	0x43, 0xbc, 0xef, 0x1b, 0xe2, 0x5d, 0x6c, 0x08, 0xfa, 0xd4, 0x13, 0xf4, 0xb5, 0x27, 0xe8, 0x5b,
	0x4f, 0xd0, 0x79, 0x4f, 0xd0, 0x8f, 0x9e, 0xa0, 0x5f, 0x3d, 0xf1, 0x2e, 0x7a, 0x82, 0x3e, 0xff,
	0x24, 0x5e, 0x75, 0x60, 0x7f, 0xfe, 0xa3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0xc0, 0x81,
	0x52, 0x42, 0x03, 0x00, 0x00,
}
