// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Packet 打包消息
func Packet(msg interface{}) (uint32, uint32, []byte, error) {
	switch msg.(type) {
	case *SWxLogin:
		b, err := msg.(*SWxLogin).Marshal()
		return 1001, 0, b, err
	case *SLogin:
		b, err := msg.(*SLogin).Marshal()
		return 1002, 0, b, err
	case *SLoginOut:
		b, err := msg.(*SLoginOut).Marshal()
		return 1003, 0, b, err
	case *SUserData:
		b, err := msg.(*SUserData).Marshal()
		return 1004, 0, b, err
	case *SGameData:
		b, err := msg.(*SGameData).Marshal()
		return 1005, 0, b, err
	case *SPing:
		b, err := msg.(*SPing).Marshal()
		return 1006, 0, b, err
	default:
		return 0, 0, []byte{}, errors.New("unknown message")
	}
}