// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Rpacket 打包消息
func Rpacket(msg interface{}) (uint32, []byte, error) {
	switch msg.(type) {
	case *CWxLogin:
		b, err := msg.(*CWxLogin).Marshal()
		return 1001, b, err
	case *CUserData:
		b, err := msg.(*CUserData).Marshal()
		return 1002, b, err
	case *CPing:
		b, err := msg.(*CPing).Marshal()
		return 1003, b, err
	default:
		return 0, []byte{}, errors.New("unknown message")
	}
}