// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Unpack 解包消息
func Unpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	case 1001:
		msg := new(CWxLogin)
		err := msg.Unmarshal(b)
		return msg, err
	case 1002:
		msg := new(CLogin)
		err := msg.Unmarshal(b)
		return msg, err
	case 1004:
		msg := new(CUserData)
		err := msg.Unmarshal(b)
		return msg, err
	case 1005:
		msg := new(CGateData)
		err := msg.Unmarshal(b)
		return msg, err
	case 1006:
		msg := new(CPing)
		err := msg.Unmarshal(b)
		return msg, err
	case 1007:
		msg := new(CPropData)
		err := msg.Unmarshal(b)
		return msg, err
	case 1008:
		msg := new(CGetCurrency)
		err := msg.Unmarshal(b)
		return msg, err
	case 1011:
		msg := new(CShop)
		err := msg.Unmarshal(b)
		return msg, err
	case 1012:
		msg := new(CBuy)
		err := msg.Unmarshal(b)
		return msg, err
	case 1013:
		msg := new(CTempShop)
		err := msg.Unmarshal(b)
		return msg, err
	case 1014:
		msg := new(COverData)
		err := msg.Unmarshal(b)
		return msg, err
	case 1015:
		msg := new(CCard)
		err := msg.Unmarshal(b)
		return msg, err
	case 1016:
		msg := new(CLoginPrize)
		err := msg.Unmarshal(b)
		return msg, err
	case 1017:
		msg := new(CUseProp)
		err := msg.Unmarshal(b)
		return msg, err
	case 1018:
		msg := new(CStart)
		err := msg.Unmarshal(b)
		return msg, err
	case 1019:
		msg := new(CShareInfo)
		err := msg.Unmarshal(b)
		return msg, err
	case 1020:
		msg := new(CInviteInfo)
		err := msg.Unmarshal(b)
		return msg, err
	case 1021:
		msg := new(CShare)
		err := msg.Unmarshal(b)
		return msg, err
	case 1022:
		msg := new(CInvite)
		err := msg.Unmarshal(b)
		return msg, err
	case 1023:
		msg := new(CGetRank)
		err := msg.Unmarshal(b)
		return msg, err
	case 1024:
		msg := new(CFight)
		err := msg.Unmarshal(b)
		return msg, err
	case 1025:
		msg := new(CFightMatch)
		err := msg.Unmarshal(b)
		return msg, err
	case 1026:
		msg := new(CFightCreate)
		err := msg.Unmarshal(b)
		return msg, err
	case 1027:
		msg := new(CFightEnter)
		err := msg.Unmarshal(b)
		return msg, err
	case 1028:
		msg := new(CFightMatchExit)
		err := msg.Unmarshal(b)
		return msg, err
	case 1029:
		msg := new(CFightChangeSet)
		err := msg.Unmarshal(b)
		return msg, err
	case 1030:
		msg := new(CFightStart)
		err := msg.Unmarshal(b)
		return msg, err
	case 1031:
		msg := new(CFightingCancelGird)
		err := msg.Unmarshal(b)
		return msg, err
	case 1032:
		msg := new(CFightingScore)
		err := msg.Unmarshal(b)
		return msg, err
	case 1033:
		msg := new(CFightingEnd)
		err := msg.Unmarshal(b)
		return msg, err
	default:
		return nil, errors.New("unknown message")
	}
}