// Code generated by tool/gen.go.
// DO NOT EDIT!

package pb

import (
	"errors"
)

//Unpack 解包消息
func Unpack(id uint32, b []byte) (interface{}, error) {
	switch id {
	case 1001:
		msg := new(CWxLogin)
		err := msg.Unmarshal(b)
		return msg, err
	case 1002:
		msg := new(CLogin)
		err := msg.Unmarshal(b)
		return msg, err
	case 1003:
		msg := new(CUserData)
		err := msg.Unmarshal(b)
		return msg, err
	case 1004:
		msg := new(CGameData)
		err := msg.Unmarshal(b)
		return msg, err
	case 1005:
		msg := new(CPing)
		err := msg.Unmarshal(b)
		return msg, err
	default:
		return nil, errors.New("unknown message")
	}
}